# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.


lst_Fib = [1, 2]
while lst_Fib[len(lst_Fib) - 1] < 4 * (10 ** 6):
    lst_Fib.append(lst_Fib[len(lst_Fib) - 2] + lst_Fib[len(lst_Fib) - 1])
print lst_Fib[len(lst_Fib) - 2]


def totaleven(lst):
    total = 0
    for number in lst:
        if number % 2 == 0:
            total += number
    return total


print totaleven(lst_Fib)
